name: angular_examples
author: Richard Griffith
description: Experiments with using Angular in Dart.
dependencies:
  angular: any
  browser: any
  simplot:
    git: git://github.com/scribeGriff/simplot.git
  convolab:
    git: git://github.com/scribeGriff/ConvoLab.git
